services:
  tranemission-next-vibemod:
    image: lowsabishi/tranemission-next-vibemod:latest
    container_name: tranemission-next-vibemod
    environment:
      TRANSMISSION_URL: http://192.168.1.10:9091
    ports:
      - "40984:80"
    restart: unless-stopped
